# Generated by Django 6.0.3 on 2026-03-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(default='Cebu City', max_length=200)),
                ('captain_name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, default='', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Barangays',
                'db_table': 'barangays',
                'ordering': ['barangay_name'],
            },
        ),
        migrations.CreateModel(
            name='BarangayMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='barangays.barangay')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_memberships', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'barangay_memberships',
                'ordering': ['-date_applied'],
                'unique_together': {('user', 'barangay')},
            },
        ),
    ]
