# Generated by Django 6.0.3 on 2026-04-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_loginotp_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginotp',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginotp',
            name='code',
            field=models.CharField(max_length=64),
        ),
    ]
