# Generated by Django 6.0.3 on 2026-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_failed_login_attempts_user_last_failed_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, default='', help_text='e.g. Secretary, Captain', max_length=100),
        ),
    ]
