# Generated by Django 6.0.3 on 2026-03-30 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barangays', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(choices=[('Cedula', 'Cedula'), ('Barangay Clearance', 'Barangay Clearance'), ('Barangay Residency', 'Barangay Residency'), ('Barangay Indigency', 'Barangay Indigency'), ('Certificate of Low Income', 'Certificate of Low Income'), ('Certificate for No Income', 'Certificate for No Income'), ('Business Permit', 'Business Permit'), ('Barangay Identification', 'Barangay Identification')], max_length=50)),
                ('tracking_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('sitio', models.CharField(blank=True, default='', max_length=200, verbose_name='Sitio / Zone / Address')),
                ('purpose', models.CharField(blank=True, default='', max_length=150)),
                ('form_data', models.JSONField(blank=True, default=dict)),
                ('appointment_time', models.CharField(choices=[('7:30 AM', '7:30 AM'), ('9:00 AM', '9:00 AM'), ('10:30 AM', '10:30 AM'), ('1:30 PM', '1:30 PM'), ('3:00 PM', '3:00 PM'), ('4:30 PM', '4:30 PM')], max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_reviewed', models.DateTimeField(blank=True, null=True)),
                ('barangay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barangays.barangay')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificate_requests',
                'ordering': ['-date_requested'],
            },
        ),
    ]
