# Generated by Django 4.2.29 on 2026-04-09 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barangays', '0001_initial'),
        ('requests_app', '0002_fix_barangay_nonnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificaterequest',
            name='barangay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_requests', to='barangays.barangay'),
        ),
    ]
