# Generated by Django 4.2.29 on 2026-04-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='attachment_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
